"""
Generate redirect entries for all URLs that the [slug] route currently handles.
These will be added to lib/redirects.ts so that removing the [slug] route
doesn't break any existing links.
"""
import json
import os

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Load manifests
with open('data/pages/services/manifest.json') as f:
    svc_manifest = json.load(f)

with open('data/pages/service-locations/manifest.json') as f:
    svc_loc_manifest = json.load(f)

with open('data/pages/locations/manifest.json') as f:
    loc_manifest = json.load(f)

redirects = []

# 1. Service slugs with hyphens → redirect to /services/{slug}
for slug in svc_manifest['services'].keys():
    if '-' in slug:
        redirects.append((f'/{slug}', f'/services/{slug}'))

# 2. Service-location combos → redirect to /services/{service}-{location}
for entry in svc_loc_manifest:
    flat_slug = f"{entry['service']}-{entry['location']}"
    # These should redirect to the matching /services/ page
    # The target is /services/{service}-{location} format
    redirects.append((f'/{flat_slug}', f'/services/{flat_slug}'))

# 3. Location-only slugs → redirect to /service-areas/{slug}
for slug in loc_manifest['locations'].keys():
    redirects.append((f'/{slug}', f'/service-areas/{slug}'))

# Output as TypeScript entries
print(f"// === [SLUG] ROUTE MIGRATION REDIRECTS ({len(redirects)} entries) ===")
print(f"// Generated by scripts/generate_slug_redirects.py")
print(f"// These replace the app/[slug]/page.tsx catch-all route")
print()

for source, dest in sorted(redirects):
    print(f"  '{source}': '{dest}',")

print(f"\n// Total: {len(redirects)} redirects")
print(f"//   - Service slugs: {len([r for r in redirects if r[1].startswith('/services/')])}")
print(f"//   - Location slugs: {len([r for r in redirects if r[1].startswith('/service-areas/')])}")
